### ISSUE TITLE
Rename to PolicyServer.Samples

### ISSUE THREAD

**Issue by LindaLawton** [PolicyServer/Samples#3]
I would like to suggest a rename something like _PolicyServer.Samples_ something along the lines of [IdentityServer4.Samples](https://github.com/IdentityServer/IdentityServer4.Samples)

When i clone it clones into a Samples directory which inst ideal.

**Comment by leastprivilege** [comment]
lol

`git clone https://github.com/PolicyServer/Samples.git PolicyServer.Samples`

;)

**Comment by LindaLawton** [comment]
I know but I kinda like consistency  :)  

Its your project if your not interested feel free to close it as a wont fix.
